#!/bin/bash
export HOMESFOLDER=C:/Users
export USERNAME=jcarl
export NODE=node.exe
export EXAMPLES=${HOMESFOLDER}/$USERNAME/www.web3d.org/x3d/content/examples/
export X3DJSONLD=${HOMESFOLDER}/$USERNAME/ScriptPreprocessor
export NODEDIR=${X3DJSONLD}/src/main/node
